@startuml

title Activity Diagram

start
:Користувач успішно оформив та сплатив замовлення;
:Програмний продукт надсилає повідомлення користувачеві, що замовлення обробляється;
:Програмний продукт надсилає замовлення до кухаря;
if (Кухар взяв замовлення у роботу) then (так)
  :Програмний продукт надсилає повідомлення користувачеві, що кухар почав готувати замовлення;
  :Кухар готує замовлення;
  if (Кухар закінчив готувати) then (так)
    :Програмний продукт оновлює статус замовлення на "готове до доставки";
    :Програмний продукт надсилає повідомлення користувачеві, що замовлення готове до доставки;
    stop
  else (ні)
    :Програмний продукт чекає, поки кухар закінчить готувати;
    repeat
      :Очікування завершення готування;
    repeat while (Кухар не закінчив готувати)
  endif
else (ні)
  :Програмний продукт чекає, поки кухар прийме замовлення у роботу;
  repeat
    :Очікування прийняття замовлення кухарем;
  repeat while (Кухар не взяв замовлення у роботу)
endif
stop

@enduml
