@startuml
hide circle
title UML-ConceptClasses

Class ГурманМеломан{
    Ім'я
    Email
    Пароль
    Номер телефону
}

Class Замовлення{
    Дата
    Статус
    АдресаГурманаМеломана
}

Class Кухар{
    Ім'я
    Email
    Пароль
}

ГурманМеломан"1" --> "0...*"Замовлення: Створює

Кухар"1" --> "*"Замовлення: Готує

@enduml
